kheuy_app/config/routes.rb
Rails.application.routes.draw do
  resources :jobs

end

kheuy_app/app/models/job.rb
class Job < ActiveRecord::Base
end

kheuy_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

kheuy_app/app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :description, :company_name, :details_link)
    end
end

kheuy_app/app/helpers/application_helper.rb
module ApplicationHelper
end

kheuy_app/app/helpers/jobs_helper.rb
module JobsHelper
end

kheuy_app/app/views/jobs/_form.html.haml
= form_for @job do |f|
  - if @job.errors.any?
    #error_explanation
      %h2= "#{pluralize(@job.errors.count, "error")} prohibited this job from being saved:"
      %ul
        - @job.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :company_name
    = f.text_field :company_name
  .field
    = f.label :details_link
    = f.text_field :details_link
  .actions
    = f.submit 'Save'

kheuy_app/app/views/jobs/edit.html.haml
%h1 Editing job

= render 'form'

= link_to 'Show', @job
\|
= link_to 'Back', jobs_path

kheuy_app/app/views/jobs/index.html.haml
%h1 Listing jobs

%table
  %thead
    %tr
      %th Title
      %th Description
      %th Company name
      %th Details link
      %th
      %th
      %th

  %tbody
    - @jobs.each do |job|
      %tr
        %td= job.title
        %td= job.description
        %td= job.company_name
        %td= job.details_link
        %td= link_to 'Show', job
        %td= link_to 'Edit', edit_job_path(job)
        %td= link_to 'Destroy', job, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Job', new_job_path

kheuy_app/app/views/jobs/new.html.haml
%h1 New job

= render 'form'

= link_to 'Back', jobs_path

kheuy_app/app/views/jobs/show.html.haml
%p#notice= notice

= @job.title
= @job.company_name
= @job.description

= @job.details_link

= link_to 'Edit', edit_job_path(@job)
\|
= link_to 'Back', jobs_path

kheuy_app/app/views/layouts/application.html.haml
!!! 5
%html
 %head
  %title liguéye
  =stylesheet_link_tag :all
  =javascript_include_tag :defaults
  =csrf_meta_tag
  
  %body
   = yield